"""initial migration

Revision ID: 29910a45ec97
Revises: 9ae2bcbd8c2b
Create Date: 2026-09-29 10:16:33.671143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29910a45ec97'
down_revision = '9ae2bcbd8c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
